// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pineda.Facturacion.Infrastructure.BillingWrite.Persistence;

#nullable disable

namespace Pineda.Facturacion.Infrastructure.BillingWrite.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260319154255_InitialSnapshotImport")]
    partial class InitialSnapshotImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.LegacyImportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BillingDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_document_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("int")
                        .HasColumnName("import_status");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("imported_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_document_type");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_table");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "SourceTable", "SourceDocumentId")
                        .IsUnique();

                    b.ToTable("legacy_import_record", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerLegacyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_legacy_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerRfc")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("customer_rfc");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_total");

                    b.Property<long>("LegacyImportRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_import_record_id");

                    b.Property<string>("LegacyOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_order_number");

                    b.Property<string>("LegacyOrderType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_order_type");

                    b.Property<string>("PaymentCondition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_condition");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("price_list_code");

                    b.Property<DateTime>("SnapshotTakenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("snapshot_taken_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_total");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("LegacyImportRecordId");

                    b.ToTable("sales_order", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("LegacyArticleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_article_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<long>("SalesOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("SatProductServiceCode")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("sat_product_service_code");

                    b.Property<string>("SatUnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sat_unit_code");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_item", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.LegacyImportRecord", null)
                        .WithMany()
                        .HasForeignKey("LegacyImportRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.SalesOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
