// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pineda.Facturacion.Infrastructure.BillingWrite.Persistence;

#nullable disable

namespace Pineda.Facturacion.Infrastructure.BillingWrite.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260319225221_AddFiscalImportStagingPreview")]
    partial class AddFiscalImportStagingPreview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.BillingDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_total");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_type");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("folio");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("PaymentCondition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_condition");

                    b.Property<string>("PaymentFormSat")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_form_sat");

                    b.Property<string>("PaymentMethodSat")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_method_sat");

                    b.Property<long>("SalesOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("Series")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("series");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_total");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("DocumentType", "Series", "Folio")
                        .IsUnique();

                    b.ToTable("billing_document", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.BillingDocumentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BillingDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_document_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_amount");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("SatProductServiceCode")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("sat_product_service_code");

                    b.Property<string>("SatUnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sat_unit_code");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxObjectCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tax_object_code");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("BillingDocumentId");

                    b.ToTable("billing_document_item", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.FiscalReceiver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CfdiUseCodeDefault")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cfdi_use_code_default");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FiscalRegimeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fiscal_regime_code");

                    b.Property<string>("ForeignTaxRegistration")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("foreign_tax_registration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("NormalizedLegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("normalized_legal_name");

                    b.Property<string>("NormalizedSearchAlias")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("normalized_search_alias");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rfc");

                    b.Property<string>("SearchAlias")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("search_alias");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLegalName");

                    b.HasIndex("NormalizedSearchAlias");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("fiscal_receiver", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.FiscalReceiverImportBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DuplicateRowsInFile")
                        .HasColumnType("int")
                        .HasColumnName("duplicate_rows_in_file");

                    b.Property<int>("ExistingMasterMatches")
                        .HasColumnType("int")
                        .HasColumnName("existing_master_matches");

                    b.Property<int>("IgnoredRows")
                        .HasColumnType("int")
                        .HasColumnName("ignored_rows");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("int")
                        .HasColumnName("invalid_rows");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_file_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("int")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.ToTable("fiscal_receiver_import_batch", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.FiscalReceiverImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("ExistingFiscalReceiverId")
                        .HasColumnType("bigint")
                        .HasColumnName("existing_fiscal_receiver_id");

                    b.Property<string>("NormalizedCfdiUseCodeDefault")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("normalized_cfdi_use_code_default");

                    b.Property<string>("NormalizedCountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("normalized_country_code");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedFiscalRegimeCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("normalized_fiscal_regime_code");

                    b.Property<string>("NormalizedForeignTaxRegistration")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("normalized_foreign_tax_registration");

                    b.Property<string>("NormalizedLegalName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("normalized_legal_name");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("NormalizedPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("normalized_postal_code");

                    b.Property<string>("NormalizedRfc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("normalized_rfc");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("raw_json");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("row_number");

                    b.Property<string>("SourceExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_external_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("SuggestedAction")
                        .HasColumnType("int")
                        .HasColumnName("suggested_action");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("NormalizedRfc");

                    b.HasIndex("BatchId", "RowNumber");

                    b.ToTable("fiscal_receiver_import_row", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.IssuerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CertificateReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("certificate_reference");

                    b.Property<string>("CfdiVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cfdi_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FiscalRegimeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fiscal_regime_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PacEnvironment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pac_environment");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postal_code");

                    b.Property<string>("PrivateKeyPasswordReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("private_key_password_reference");

                    b.Property<string>("PrivateKeyReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("private_key_reference");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rfc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("issuer_profile", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.LegacyImportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BillingDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_document_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("int")
                        .HasColumnName("import_status");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("imported_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_document_type");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_table");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "SourceTable", "SourceDocumentId")
                        .IsUnique();

                    b.ToTable("legacy_import_record", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.ProductFiscalProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultUnitText")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("default_unit_text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("normalized_description");

                    b.Property<string>("SatProductServiceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sat_product_service_code");

                    b.Property<string>("SatUnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sat_unit_code");

                    b.Property<string>("TaxObjectCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tax_object_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("InternalCode")
                        .IsUnique();

                    b.HasIndex("NormalizedDescription");

                    b.ToTable("product_fiscal_profile", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.ProductFiscalProfileImportBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultTaxObjectCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("default_tax_object_code");

                    b.Property<string>("DefaultUnitText")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("default_unit_text");

                    b.Property<decimal?>("DefaultVatRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("default_vat_rate");

                    b.Property<int>("DuplicateRowsInFile")
                        .HasColumnType("int")
                        .HasColumnName("duplicate_rows_in_file");

                    b.Property<int>("ExistingMasterMatches")
                        .HasColumnType("int")
                        .HasColumnName("existing_master_matches");

                    b.Property<int>("IgnoredRows")
                        .HasColumnType("int")
                        .HasColumnName("ignored_rows");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("int")
                        .HasColumnName("invalid_rows");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_file_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("int")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.ToTable("product_fiscal_profile_import_batch", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.ProductFiscalProfileImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("ExistingProductFiscalProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("existing_product_fiscal_profile_id");

                    b.Property<string>("NormalizedDefaultUnitText")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_default_unit_text");

                    b.Property<string>("NormalizedDescription")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("normalized_description");

                    b.Property<string>("NormalizedInternalCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("normalized_internal_code");

                    b.Property<string>("NormalizedSatProductServiceCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("normalized_sat_product_service_code");

                    b.Property<string>("NormalizedSatUnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("normalized_sat_unit_code");

                    b.Property<string>("NormalizedTaxObjectCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("normalized_tax_object_code");

                    b.Property<decimal?>("NormalizedVatRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("normalized_vat_rate");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("raw_json");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("row_number");

                    b.Property<string>("SourceExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_external_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("SuggestedAction")
                        .HasColumnType("int")
                        .HasColumnName("suggested_action");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("NormalizedInternalCode");

                    b.HasIndex("BatchId", "RowNumber");

                    b.ToTable("product_fiscal_profile_import_row", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerLegacyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_legacy_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerRfc")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("customer_rfc");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_total");

                    b.Property<long>("LegacyImportRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_import_record_id");

                    b.Property<string>("LegacyOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_order_number");

                    b.Property<string>("LegacyOrderType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_order_type");

                    b.Property<string>("PaymentCondition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_condition");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("price_list_code");

                    b.Property<DateTime>("SnapshotTakenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("snapshot_taken_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_total");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("LegacyImportRecordId");

                    b.ToTable("sales_order", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("LegacyArticleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("legacy_article_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("quantity");

                    b.Property<long>("SalesOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("SatProductServiceCode")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("sat_product_service_code");

                    b.Property<string>("SatUnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sat_unit_code");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_item", (string)null);
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.BillingDocument", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.SalesOrder", null)
                        .WithMany()
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.BillingDocumentItem", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.BillingDocument", null)
                        .WithMany("Items")
                        .HasForeignKey("BillingDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.FiscalReceiverImportRow", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.FiscalReceiverImportBatch", null)
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.ProductFiscalProfileImportRow", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.ProductFiscalProfileImportBatch", null)
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.LegacyImportRecord", null)
                        .WithMany()
                        .HasForeignKey("LegacyImportRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("Pineda.Facturacion.Domain.Entities.SalesOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.BillingDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.FiscalReceiverImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.ProductFiscalProfileImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Pineda.Facturacion.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
