using Microsoft.Extensions.DependencyInjection;
using Pineda.Facturacion.Application.UseCases.AccountsReceivable;
using Pineda.Facturacion.Application.UseCases.Audit;
using Pineda.Facturacion.Application.UseCases.Auth;
using Pineda.Facturacion.Application.UseCases.BillingDocuments;
using Pineda.Facturacion.Application.UseCases.CreateBillingDocument;
using Pineda.Facturacion.Application.UseCases.FiscalReceivers;
using Pineda.Facturacion.Application.UseCases.FiscalDocuments;
using Pineda.Facturacion.Application.UseCases.ImportLegacyOrder;
using Pineda.Facturacion.Application.UseCases.ImportLegacyOrderPreview;
using Pineda.Facturacion.Application.UseCases.IssuerProfiles;
using Pineda.Facturacion.Application.UseCases.Orders;
using Pineda.Facturacion.Application.UseCases.PaymentComplements;
using Pineda.Facturacion.Application.UseCases.ProductFiscalProfiles;
using Pineda.Facturacion.Application.UseCases.SatProductServices;

namespace Pineda.Facturacion.Application.DependencyInjection;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddScoped<ImportLegacyOrderService>();
        services.AddScoped<ReimportLegacyOrderService>();
        services.AddScoped<PreviewLegacyOrderImportService>();
        services.AddScoped<LegacyImportRevisionRecorder>();
        services.AddScoped<ListLegacyImportRevisionsService>();
        services.AddScoped<SearchLegacyOrdersService>();
        services.AddScoped<ListAuditEventsService>();
        services.AddScoped<LoginService>();
        services.AddScoped<GetCurrentUserService>();
        services.AddScoped<CreateBillingDocumentService>();
        services.AddScoped<GetBillingDocumentLookupByIdService>();
        services.AddScoped<SearchBillingDocumentsService>();
        services.AddScoped<ListPendingBillingItemsService>();
        services.AddScoped<UpdateBillingDocumentOrderAssociationService>();
        services.AddScoped<RemoveBillingDocumentItemService>();
        services.AddScoped<AssignPendingBillingItemsService>();
        services.AddScoped<CreateAccountsReceivableInvoiceFromFiscalDocumentService>();
        services.AddScoped<EnsureAccountsReceivableInvoiceForFiscalDocumentService>();
        services.AddScoped<GetAccountsReceivableInvoiceByFiscalDocumentIdService>();
        services.AddScoped<GetAccountsReceivableInvoiceDetailService>();
        services.AddScoped<SearchAccountsReceivablePortfolioService>();
        services.AddScoped<GetAccountsReceivableReceiverWorkspaceService>();
        services.AddScoped<SynchronizeAccountsReceivableCollectionStateService>();
        services.AddScoped<CreateCollectionCommitmentService>();
        services.AddScoped<ListCollectionCommitmentsByInvoiceIdService>();
        services.AddScoped<CreateCollectionNoteService>();
        services.AddScoped<ListCollectionNotesByInvoiceIdService>();
        services.AddScoped<SearchAccountsReceivablePaymentsService>();
        services.AddScoped<CreateAccountsReceivablePaymentService>();
        services.AddScoped<GetAccountsReceivablePaymentByIdService>();
        services.AddScoped<ApplyAccountsReceivablePaymentService>();
        services.AddScoped<SetAccountsReceivablePaymentUnappliedDispositionService>();
        services.AddScoped<PreparePaymentComplementService>();
        services.AddScoped<GetPaymentComplementByPaymentIdService>();
        services.AddScoped<SearchInternalRepBaseDocumentsService>();
        services.AddScoped<SearchExternalRepBaseDocumentsService>();
        services.AddScoped<SearchRepBaseDocumentsService>();
        services.AddScoped<SearchRepAttentionItemsService>();
        services.AddScoped<BulkRefreshInternalRepBaseDocumentsService>();
        services.AddScoped<BulkRefreshExternalRepBaseDocumentsService>();
        services.AddScoped<BulkRefreshRepBaseDocumentsService>();
        services.AddScoped<GetInternalRepBaseDocumentByFiscalDocumentIdService>();
        services.AddScoped<ImportExternalRepBaseDocumentFromXmlService>();
        services.AddScoped<GetExternalRepBaseDocumentByIdService>();
        services.AddScoped<RegisterInternalRepBaseDocumentPaymentService>();
        services.AddScoped<PrepareInternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<StampInternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<RefreshInternalRepBaseDocumentPaymentComplementStatusService>();
        services.AddScoped<CancelInternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<RegisterExternalRepBaseDocumentPaymentService>();
        services.AddScoped<PrepareExternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<StampExternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<RefreshExternalRepBaseDocumentPaymentComplementStatusService>();
        services.AddScoped<CancelExternalRepBaseDocumentPaymentComplementService>();
        services.AddScoped<StampPaymentComplementService>();
        services.AddScoped<GetPaymentComplementStampByPaymentComplementIdService>();
        services.AddScoped<CancelPaymentComplementService>();
        services.AddScoped<GetPaymentComplementCancellationByPaymentComplementIdService>();
        services.AddScoped<RefreshPaymentComplementStatusService>();
        services.AddScoped<PrepareFiscalDocumentService>();
        services.AddScoped<SearchIssuedFiscalDocumentsService>();
        services.AddScoped<ListIssuedFiscalDocumentSpecialFieldsService>();
        services.AddScoped<GetFiscalDocumentByIdService>();
        services.AddScoped<SyncFiscalDocumentSpecialFieldsService>();
        services.AddScoped<GetFiscalStampByFiscalDocumentIdService>();
        services.AddScoped<QueryRemoteFiscalStampService>();
        services.AddScoped<GetFiscalDocumentPdfService>();
        services.AddScoped<GetFiscalDocumentEmailDraftService>();
        services.AddScoped<StampFiscalDocumentService>();
        services.AddScoped<SendFiscalDocumentEmailService>();
        services.AddScoped<GetFiscalCancellationByFiscalDocumentIdService>();
        services.AddScoped<CancelFiscalDocumentService>();
        services.AddScoped<RefreshFiscalDocumentStatusService>();
        services.AddScoped<ListPendingFiscalCancellationAuthorizationsService>();
        services.AddScoped<RespondFiscalCancellationAuthorizationService>();
        services.AddScoped<CreateIssuerProfileService>();
        services.AddScoped<UpdateIssuerProfileService>();
        services.AddScoped<GetActiveIssuerProfileService>();
        services.AddScoped<UploadIssuerProfileLogoService>();
        services.AddScoped<GetIssuerProfileLogoService>();
        services.AddScoped<RemoveIssuerProfileLogoService>();
        services.AddScoped<SearchFiscalReceiversService>();
        services.AddScoped<GetFiscalReceiverByRfcService>();
        services.AddScoped<CreateFiscalReceiverService>();
        services.AddScoped<UpdateFiscalReceiverService>();
        services.AddScoped<PreviewFiscalReceiverImportFromExcelService>();
        services.AddScoped<GetFiscalReceiverImportBatchService>();
        services.AddScoped<ListFiscalReceiverImportRowsService>();
        services.AddScoped<ApplyFiscalReceiverImportBatchService>();
        services.AddScoped<SearchProductFiscalProfilesService>();
        services.AddScoped<SearchSatProductServicesService>();
        services.AddScoped<GetProductFiscalProfileByInternalCodeService>();
        services.AddScoped<CreateProductFiscalProfileService>();
        services.AddScoped<UpdateProductFiscalProfileService>();
        services.AddScoped<PreviewProductFiscalProfileImportFromExcelService>();
        services.AddScoped<GetProductFiscalProfileImportBatchService>();
        services.AddScoped<ListProductFiscalProfileImportRowsService>();
        services.AddScoped<ApplyProductFiscalProfileImportBatchService>();
        return services;
    }
}
